const express=require('express');
const path=require('path');
const weatherRoute=require('./routes/weather');
const app=express();
app.set('view engine','ejs');
app.set('views',path.join(__dirname,'views'));
app.use(express.static(path.join(__dirname,'public')));
app.use('/',weatherRoute);
const port=3000;
app.listen(port,()=>console.log('Running on '+port));